version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: advisorai-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: advisor_ai_hub
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - advisorai-network

  redis:
    image: redis:7-alpine
    container_name: advisorai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - advisorai-network

networks:
  advisorai-network:
    driver: bridge

volumes:
  postgres_dev_data:
  redis_dev_data:
